# .ruff.toml
line-length = 100
target-version = "py312"

exclude = [
    "venv",
    "migrations",
    "static",
    "templates",
    "docs",
]

[lint]
select = ["E", "F", "W", "I"]   # pycodestyle errors, pyflakes, warnings, import sorting
ignore = []

[format]
quote-style = "single"