# Generated by Django 6.1 on 2026-08-30 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.program')),
            ],
        ),
    ]
