# Generated by Django 6.1 on 2026-09-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_assessment_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='assessment',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused')], db_index=True, default='PRESENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DROPPED', 'Dropped'), ('COMPLETED', 'Completed')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='grade',
            name='marks',
            field=models.IntegerField(db_index=True),
        ),
    ]
